Merge from opensuse-11-1 branch, presumably needed here, too:
Merge from opensuse-11-1 branch, presumably needed here, too:

* patches/dev300/layoutdialogs2-development.diff
(toolkit/source/layout/core/container.hxx): Mark the Container
class TOOLKIT_DLLPUBLIC so that sfx2 builds on Win32 without an
undefined reference to public: virtual bool __thiscall
layoutimpl::Container::emptyVisible(void).